gcp_project   = "oct29gcpproject"
gcp_region    = "us-central1"
//gcp_auth_file = "tf-key.json"
gcp_zone      = "us-central1-c"
//gcp_network = "myvpcnetwork"
gcp_instancename      = "terraform-custom-network"
gcp_machinetype = "e2-micro"
//gcp_auth_file = "./SA_key.json"
